### ISSUE TITLE
Dplayer支持问题

### ISSUE THREAD

**Issue by aston314** [simpleRobort/TV-Focus.js#1]
首先感谢楼主提供这么优秀的脚本。
我目前在TV上使用Dplayer进行视频播放，使用楼主的脚本，有时候可以用遥控器操作Dplayer，有时候不行。

我把焦点定位在.MacPlayer的div上，不知道这样操作是否正确？

**Comment by simpleRobort** [comment]
不好意思之前一直没关注issue，你后续应该是加我微信我们商讨解决了吧，我对你这个Dplayer有印象
