### ISSUE TITLE
焦点切换的时候会有位移，如何消除位移呢？

### ISSUE THREAD

**Issue by tizh** [simpleRobort/TV-Focus.js#2]
焦点切换的时候会有位移，如何消除位移呢？

**Comment by simpleRobort** [comment]
位移指的是？或许你可以来一个小视频？

**Comment by tizh** [comment]
> 
基本使用测试地址demo1，当焦点移动到某一个DOM上时，文字会动一下。

**Comment by simpleRobort** [comment]
这个是因为.focus的class会给予div2像素的边框，因此导致的文字推移，这个属于css问题，例如可以这么解决：给.focus一个新的css属性(margin: -2px 0 0 -2px;)来抵消2px边框导致的位移
![20230221174210_rec_](https://user-images.githubusercontent.com/83385371/220308030-31257ec8-5fd2-47d2-828e-6e6bda24eca8.gif)
